#!/usr/bin/env python3
"""Thesis-wide bibliography: resolve [@key] citations to numbers.

Single source of truth is BIBLIOGRAPHY.md at the repository root, which holds
one entry per work under a stable key. Section files cite keys; numbers are
assigned here by first appearance across the thesis, in reading order, and
rendered into the assembled chapter files. Nothing is ever renumbered by hand.

    python3 tools/bibliography.py check     # report unresolved / uncited keys
    python3 tools/bibliography.py render    # rewrite assembled chapters + emit
                                            # BIBLIOGRAPHY_NUMBERED.md

Add a chapter by extending THESIS_ORDER below. Order matters: it defines the
numbering.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BIB = ROOT / "BIBLIOGRAPHY.md"
RENDERED = ROOT / "BIBLIOGRAPHY_NUMBERED.md"

# Chapters in thesis reading order: (section-file glob, assembled file).
# Add Chapters 1, 4, 5 and 6 here as they are written.
THESIS_ORDER = [
    ("Thesis_Chapter2_Background/0[1-9]_2*.md",
     "Thesis_Chapter2_Background/00_Chapter2_Complete.md"),
    ("Thesis_Chapter3_LiteratureReview/Tech-wise/[0-9][0-9]_3.*.md",
     "Thesis_Chapter3_LiteratureReview/Tech-wise/00_Chapter3_Complete.md"),
    ("Thesis_Chapter4_Methodology/0[1-9]_4.*.md",
     "Thesis_Chapter4_Methodology/00_Chapter4_Complete.md"),
    ("Thesis_Chapter5_Results/0[1-9]_5.*.md",
     "Thesis_Chapter5_Results/00_Chapter5_Complete.md"),
]

CITE = re.compile(r"\[@([A-Za-z0-9]+(?:\s*;\s*@[A-Za-z0-9]+)*)\]")
ENTRY = re.compile(r"^### (\S+)\s*$", re.M)
# Spans where a bracket is not a citation.
MASKS = [re.compile(r"^```.*?^```", re.S | re.M),
         re.compile(r"`[^`\n]+`"),
         re.compile(r"\$[^$\n]+\$")]


def load_entries():
    """key -> formatted reference text, preserving file order."""
    text = BIB.read_text(encoding="utf-8")
    out, parts = {}, ENTRY.split(text)
    for i in range(1, len(parts), 2):
        body = parts[i + 1].strip().split("\n\n")[0].strip()
        out[parts[i]] = " ".join(body.split())
    return out


def section_files():
    for glob, _ in THESIS_ORDER:
        base, pattern = glob.rsplit("/", 1)
        yield from sorted((ROOT / base).glob(pattern))


def assign_numbers():
    """key -> number, by first appearance across the thesis in reading order."""
    order, seen = [], set()
    for path in section_files():
        for m in CITE.finditer(path.read_text(encoding="utf-8")):
            for key in (k.strip().lstrip("@") for k in m.group(1).split(";")):
                if key not in seen:
                    seen.add(key)
                    order.append(key)
    return {k: i for i, k in enumerate(order, 1)}


def resolve(text, numbers):
    """Replace [@key] / [@a; @b] with [n] / [n, m], leaving code and maths alone."""
    spans = [m.span() for rx in MASKS for m in rx.finditer(text)]
    out, last = [], 0
    for m in CITE.finditer(text):
        if any(a <= m.start() and m.end() <= b for a, b in spans):
            continue
        keys = [k.strip().lstrip("@") for k in m.group(1).split(";")]
        missing = [k for k in keys if k not in numbers]
        if missing:
            sys.exit(f"error: unknown citation key(s) {missing} in {m.group(0)}")
        out.append(text[last:m.start()])
        out.append("[" + ", ".join(str(numbers[k]) for k in keys) + "]")
        last = m.end()
    out.append(text[last:])
    return "".join(out)


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    entries, numbers = load_entries(), assign_numbers()
    cited, known = set(numbers), set(entries)

    if cmd == "check":
        ghost, unused = sorted(cited - known), sorted(known - cited)
        print(f"bibliography entries : {len(entries)}")
        print(f"keys cited           : {len(cited)}")
        print(f"unknown keys cited   : {ghost or 'none'}")
        print(f"entries never cited  : {unused or 'none'}")
        return 0 if not ghost and not unused else 1

    if cmd == "render":
        for _, assembled in THESIS_ORDER:
            p = ROOT / assembled
            if not p.exists():
                print(f"skip (missing): {assembled}"); continue
            p.write_text(resolve(p.read_text(encoding="utf-8"), numbers), encoding="utf-8")
            print(f"rendered {assembled}")
        lines = ["# Bibliography", "",
                 "Generated by `tools/bibliography.py render`. Do not edit — "
                 "edit `BIBLIOGRAPHY.md` and re-render.", "", "---", ""]
        for key, n in sorted(numbers.items(), key=lambda kv: kv[1]):
            lines += [f"[{n}] {entries[key]}", ""]
        RENDERED.write_text("\n".join(lines), encoding="utf-8")
        print(f"wrote {RENDERED.name} — {len(numbers)} numbered entries")
        return 0

    sys.exit(f"unknown command {cmd!r}; use 'check' or 'render'")


if __name__ == "__main__":
    sys.exit(main())
